  
name: "Baselines"
on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 8 * * 2"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 1 # otherwise, you will failed to push refs to dest repo

    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      
    - name: Install R dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev libxml2-dev
        Rscript -e 'install.packages(c("forecast", "MMWRweek"))'

    - name: Setup Git
      run: |
        echo "=============================================================================="
        echo "Freeing up disk space on CI system"
        echo "=============================================================================="
        echo "Listing 100 largest packages"
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        df -h
        echo "Removing large packages"
        # sudo apt-get remove -y '^ghc-8.*'
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
        echo "Removing large directories"
        # deleting 15GB
        rm -rf /usr/share/dotnet/
        df -h
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Create Ensembles"
    
    - name: Create Baselines
      env:
        AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        cd ./code/baselines
        # create baselines
        Rscript KIT-baseline.R
        Rscript KIT-extrapolation_baseline.R
        Rscript KIT-time_series_baseline.R
        cd ../../
        
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        commit-message: Update Baselines
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: baseline
        delete-branch: true
        title: 'Update baselines'
        body: |
          Update baselines
        labels: |
          automated pr
        reviewers: jbracher
